Update bash_function

diff --git a/bash_function b/bash_function
--- a/bash_function
+++ b/bash_function
@@ -24,43 +24,247 @@ RESULT_DEFAULT="tput sgr0"
 #######################################
 
 
-function progress_bar() {
+CODE_SAVE_CURSOR="\033[s"
+CODE_RESTORE_CURSOR="\033[u"
+CODE_CURSOR_IN_SCROLL_AREA="\033[1A"
+COLOR_FG="\e[30m"
+COLOR_BG="\e[42m"
+COLOR_BG_BLOCKED="\e[43m"
+RESTORE_FG="\e[39m"
+RESTORE_BG="\e[49m"
 
-FOOTER_LINES=1
-TERM_HEIGHT=$(tput lines)
-SCROLL_START_LINE=$((FOOTER_LINES + 1))
-SCROLL_END_LINE=$((TERM_HEIGHT))
-FOOTER_START_INDEX=$((TERM_HEIGHT))
+# Variables
+PROGRESS_BLOCKED="false"
+TRAPPING_ENABLED="false"
+ETA_ENABLED="false"
+TRAP_SET="false"
+
+CURRENT_NR_LINES=0
+PROGRESS_TITLE=""
+PROGRESS_TOTAL=100
+PROGRESS_START=0
+BLOCKED_START=0
+
+
+# shellcheck disable=SC2120
+setup_scroll_area() {
+    # If trapping is enabled, we will want to activate it whenever we setup the scroll area and remove it when we break the scroll area
+    if [ "$TRAPPING_ENABLED" = "true" ]; then
+        trap_on_interrupt
+    fi
+
+    # Handle first parameter: alternative progress bar title
+    [ -n "$1" ] && PROGRESS_TITLE="$1" || PROGRESS_TITLE="Progress"
+
+    # Handle second parameter : alternative total count
+    [ -n "$2" ] && PROGRESS_TOTAL=$2 || PROGRESS_TOTAL=100
+
+    lines=$(tput lines)
+    CURRENT_NR_LINES=$lines
+    lines=$((lines-1))
+    # Scroll down a bit to avoid visual glitch when the screen area shrinks by one row
+    echo -en "\n"
+
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+    # Set scroll region (this will place the cursor in the top left)
+    echo -en "\033[0;${lines}r"
+
+    # Restore cursor but ensure its inside the scrolling area
+    echo -en "$CODE_RESTORE_CURSOR"
+    echo -en "$CODE_CURSOR_IN_SCROLL_AREA"
+
+    # Store start timestamp to compute ETA
+    if [ "$ETA_ENABLED" = "true" ]; then
+      PROGRESS_START=$( date +%s )
+    fi
+
+    # Start empty progress bar
+    draw_progress_bar 0
+}
+
+destroy_scroll_area() {
+    lines=$(tput lines)
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+    # Set scroll region (this will place the cursor in the top left)
+    echo -en "\033[0;${lines}r"
+
+    # Restore cursor but ensure its inside the scrolling area
+    echo -en "$CODE_RESTORE_CURSOR"
+    echo -en "$CODE_CURSOR_IN_SCROLL_AREA"
+
+    # We are done so clear the scroll bar
+    clear_progress_bar
+
+    # Scroll down a bit to avoid visual glitch when the screen area grows by one row
+    echo -en "\n\n"
+
+    # Reset title for next usage
+    PROGRESS_TITLE=""
+
+    # Once the scroll area is cleared, we want to remove any trap previously set. Otherwise, ctrl+c will exit our shell
+    if [ "$TRAP_SET" = "true" ]; then
+        trap - EXIT
+    fi
+}
+
+format_eta() {
+    local T=$1
+    local D=$((T/60/60/24))
+    local H=$((T/60/60%24))
+    local M=$((T/60%60))
+    local S=$((T%60))
+    [ $D -eq 0 -a $H -eq 0 -a $M -eq 0 -a $S -eq 0 ] && echo "--:--:--" && return
+    [ $D -gt 0 ] && printf '%d days, ' $D
+    printf 'ETA: %d:%02.f:%02.f' $H $M $S
+}
+
+draw_progress_bar() {
+    eta=""
+    if [ "$ETA_ENABLED" = "true" -a $1 -gt 0 ]; then
+        if [ "$PROGRESS_BLOCKED" = "true" ]; then
+            blocked_duration=$(($(date +%s)-$BLOCKED_START))
+            PROGRESS_START=$((PROGRESS_START+blocked_duration))
+        fi
+        running_time=$(($(date +%s)-PROGRESS_START))
+        total_time=$((PROGRESS_TOTAL*running_time/$1))
+        eta=$( format_eta $(($total_time-$running_time)) )
+    fi
+
+    percentage=$1
+    if [ $PROGRESS_TOTAL -ne 100 ]
+    then
+	[ $PROGRESS_TOTAL -eq 0 ] && percentage=100 || percentage=$((percentage*100/$PROGRESS_TOTAL))
+    fi
+    extra=$2
+
+    lines=$(tput lines)
+    lines=$((lines))
+
+    # Check if the window has been resized. If so, reset the scroll area
+    if [ "$lines" -ne "$CURRENT_NR_LINES" ]; then
+        setup_scroll_area
+    fi
+
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+
+    # Move cursor position to last row
+    echo -en "\033[${lines};0f"
+
+    # Clear progress bar
+    tput el
+
+    # Draw progress bar
+    PROGRESS_BLOCKED="false"
+    print_bar_text $percentage "$extra" "$eta"
+
+    # Restore cursor position
+    echo -en "$CODE_RESTORE_CURSOR"
+}
+
+block_progress_bar() {
+    percentage=$1
+    lines=$(tput lines)
+    lines=$((lines))
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+
+    # Move cursor position to last row
+    echo -en "\033[${lines};0f"
+
+    # Clear progress bar
+    tput el
+
+    # Draw progress bar
+    PROGRESS_BLOCKED="true"
+    BLOCKED_START=$( date +%s )
+    print_bar_text $percentage
+
+    # Restore cursor position
+    echo -en "$CODE_RESTORE_CURSOR"
+}
+
+clear_progress_bar() {
+    lines=$(tput lines)
+    lines=$((lines))
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+
+    # Move cursor position to last row
+    echo -en "\033[${lines};0f"
+
+    # clear progress bar
+    tput el
+
+    # Restore cursor position
+    echo -en "$CODE_RESTORE_CURSOR"
+}
+
+print_bar_text() {
+    local percentage=$1
+    local extra=$2
+    [ -n "$extra" ] && extra=" ($extra)"
+    local eta=$3
+    if [ -n "$eta" ]; then
+        [ -n "$extra" ] && extra="$extra "
+        extra="$extra$eta"
+    fi
+    local cols=$(tput cols)
+    bar_size=$((cols-9-${#PROGRESS_TITLE}-${#extra}))
+
+    local color="${COLOR_FG}${COLOR_BG}"
+    if [ "$PROGRESS_BLOCKED" = "true" ]; then
+        color="${COLOR_FG}${COLOR_BG_BLOCKED}"
+    fi
+
+    # Prepare progress bar
+    complete_size=$(((bar_size*percentage)/100))
+    remainder_size=$((bar_size-complete_size))
+    progress_bar=$(echo -ne "["; echo -en "${color}"; printf_new "#" $complete_size; echo -en "${RESTORE_FG}${RESTORE_BG}"; printf_new "." $remainder_size; echo -ne "]");
+
+    # Print progress bar
+    echo -ne " $PROGRESS_TITLE ${percentage}% ${progress_bar}${extra}"
+}
+
+enable_trapping() {
+    TRAPPING_ENABLED="true"
+}
+
+trap_on_interrupt() {
+    # If this function is called, we setup an interrupt handler to cleanup the progress bar
+    TRAP_SET="true"
+    trap cleanup_on_interrupt EXIT
+}
+
+cleanup_on_interrupt() {
+    destroy_scroll_area
+    exit
+}
+
+printf_new() {
+    str=$1
+    num=$2
+    v=$(printf "%-${num}s" "$str")
+    echo -ne "${v// /$str}"
+}
+
+# 아래 형태로 호출시 해당 명령어 혹은 함수들 실행하며 실행된 진척도를 ubuntu pakage installer 형태로 출력
+# progress_bar "함수" "command" "형태로 호출해서 사용가능"
+# Use progress_bar function from inside script
+# progress_bar 호출후 destroy_scroll_area 함수 호출하여 화면 하단 영역 삭제 해야함 미호출시 progress bar 가 지저분하게 터미널에 남음
+
+function progress_bar() {
 
   local CMDS=("${@}")
   local MAX_STEPS=$#
-  local BAR_SIZE="##############################"
-  local MAX_BAR_SIZE="${#BAR_SIZE}"
-  local CLEAR_LINE="\\033[K"
-  tput clear
 
-  tput civis -- invisible
-
-  tput cup 0 0
-  tput el
-  echo -ne "\\r[${BAR_SIZE:0:percBar}] $perc %$CLEAR_LINE"
   for step in "${!CMDS[@]}"; do
-    perc=$((step * 100 / MAX_STEPS))
-    percBar=$((perc * MAX_BAR_SIZE / 100))
-    ${CMDS[$step]}
-    tput sc
-    tput cup 0 0
-    tput el
-
     perc=$(((step + 1) * 100 / MAX_STEPS))
-    percBar=$((perc * MAX_BAR_SIZE / 100))
-    echo -ne "\\r[${BAR_SIZE:0:percBar}] $perc %$CLEAR_LINE"
-    sleep 0.1
-    tput rc
+    ${CMDS[$step]}
+    draw_progress_bar $perc
   done
-
-  tput cnorm -- normal
-  tput el
 }
 
 #######################################
